name: permissions

on: 
    push:
        paths-ignore:
            - '*.json'
    pull_request:
        paths-ignore:
            - '*.json'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
